### ISSUE TITLE
Yes_No_recognitionとの統合

### ISSUE THREAD

**Issue by Nenetti** [rionehome/sound_system_ros#3]
# 概要
Yes No Recognition 結局sphinx使ってるだけ、かつソースも短いので、この程度ならわざわざパッケージで管理する必要はないと考えられる
よってこれらの統合を具申

# 対象リポジトリ
・ sound_system_ros
・ yes_no_recognition

# 変更点
・ yes_no_recognition の機能をsound_system_rosに統合
・ yes_no_recognition のリポジトリ削除
・ sound_system_ros内にyes_no_recognition用のlaunchファイルを追加

**Comment by HiroRittsu** [comment]
統合はお願いします。ただ、yes_no_recognition のリポジトリ削除は待って欲しい。色んなとこにそのリポジトリ使ってるから、とりあえずある程度リファクタリング終わってからで。

**Comment by Nenetti** [comment]
おっけー

**Comment by Nenetti** [comment]
# 作業完了
動作確認済み
呼び出しは/sound_system_ros/launch/yes_no_recognition.launchを参照

# 変更点 
yes_no_recognitionの機能をsound_systemに統合

yes_no_recognition.launchを追加
dict、gramの設定パラメータ、remapを使用
sphinx.py の修正


# 他報告
リポジトリ [yes_no_recognition](https://github.com/rionehome/yes_no_recognition) の削除は念の為、見送る
